### ISSUE TITLE
ng build prod stuck at 95% after adding contents of the new esri-map files

### ISSUE THREAD

**Issue by banchana** [Esri/angular-cli-esri-map#14]
I am using angular 6 and esri-loader. 
I followed an example that ESRI has on GitHub at https://github.com/Esri/angular-cli-esri-map.  Here are the exact steps that I did to confirm.
 
Follow the instructions on the sample through the part where you generate a new component named esri-map.  Before adding the contents of the new esri-map files, confirm that you can successfully build using “ng build --prod”.  Remove the “sourceMap”: false from the production configurations section of the angular.json file.  Confirm that the “ng build --prod” still works.
 
Continue on with the sample.  After making the other changes up to the point where they ask you to run “ng serve” try and build using “ng build --prod”.  
 
For me, the build stalls at 95% at this point.  If I reinsert the sourceMap: false “ng build --prod” succeeds
 
I am not sure why…any information would be greatly appreciated.

Thanks!

**Comment by andygup** [comment]
Hi @banchana, 

1) Can you confirm the github repo where you are getting those instructions from? It's not this repo.

2) Include the console output that shows where the build process is hanging?

3) Also, if you can create a working example on stackblitz that would help with troubleshooting. Here's an example: https://stackblitz.com/edit/angular-cli-esri

**Comment by andygup** [comment]
Closing...feel free to reopen if needed.
