### ISSUE TITLE
Where is the documentation for markers, polylines, infoboxes, etc.?

### ISSUE THREAD

**Issue by Conner05** [Esri/angular-cli-esri-map#18]
I would like to use the esri-map in an Angular 7 application as an interactive map that I can feed a datasource of markers and polylines. Is that a capability of this module?

**Comment by andygup** [comment]
@Conner05 any functionality that works in the ArcGIS API for JavaScript should work using the patterns described in this repo. Underneath the hood, this repo uses [`esri-loader`](https://github.com/Esri/esri-loader) to load the ArcGIS API for JavaScript modules.

**Comment by Conner05** [comment]
@andygup Will I still be able to use existing angular services and components to interact with the ArcGIS API? For example, if I have an http call in my `ngOnInit()` method that makes a call to an Angular service (`service.ts`) which then retrieves data from some API and set some component variable with that result can I easily pass that data onto the map? If so, is there any documentation or examples I can reference?

**Comment by andygup** [comment]
@Conner05 Yes. You might take a look at this repo from an Angular presentation we did last year at DevSummit and see if that helps. It's the most comprehensive set of of updated samples that we have: https://github.com/sean-olson-e/Angular-and-the-ArcGIS-API-for-JavaScript/tree/master/sample_apps

**Comment by andygup** [comment]
Closing as answered.
