### ISSUE TITLE
loading ArcGISDynamicMapServiceLayer return 404 error

### ISSUE THREAD

**Issue by abhishekhingu** [Esri/angular-cli-esri-map#27]
const [EsriMap, EsriMapView,FeatureLayer,DynamicLayer,ClassBreaksRenderer] = await loadModules([
        'esri/Map',
        'esri/views/MapView',
        'esri/layers/FeatureLayer',
        'esri/layers/ArcGISDynamicMapServiceLayer',
        'esri/renderers/ClassBreaksRenderer'
      ]);
I am getting 404 error when try to load ArcGISDynamicMapServiceLayer using arcgis JavaScript API version 4.10.

**Comment by andygup** [comment]
@abhishekhingu There isn't an `ArcGISDynamicMapServiceLayer` in version 4.10. It's been renamed to `"esri/layers/MapImageLayer"`.

References:
https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-MapImageLayer.html 
https://developers.arcgis.com/javascript/latest/guide/functionality-matrix/index.html#arcgisdynamicmapservicelayer

I'll go ahead and close this.
