### ISSUE TITLE
Using esri Map with Angular - JavaScript 4.10, TemplatePopup showing randomly on the Webpage

### ISSUE THREAD

**Issue by MohamadMousheimish** [Esri/angular-cli-esri-map#28]
I'm using esri map with Angular. I'm getting the points from the server. And for each point I'm adding a graphic.
For each graphic (point) added, I'm setting a PopupTemplate.
Everything works fine for the graphics, but an empty PopupTemplate is showing randomly when pressing the second (right) click of the mouse.
Here's how I'm setting the PopupTemplate:
![image](https://user-images.githubusercontent.com/28274119/53648151-de36f900-3c47-11e9-93ad-b730b2bc30ec.png)

Here's a normal popup working fine:
![image](https://user-images.githubusercontent.com/28274119/53648572-e17eb480-3c48-11e9-8b96-79a4a7a5342f.png)

And here's the random popup showing randomly on the right click of the mouse:
![image](https://user-images.githubusercontent.com/28274119/53648604-f8250b80-3c48-11e9-83a1-c86d0741db24.png)

So can anybody tell me why the random popup is being displayed when pressing the right click of the mouse ?
Please and thank you.

**Comment by andygup** [comment]
Oops, I missed this. Did you solve the issue?
