### ISSUE TITLE
Update to Angular 8

### ISSUE THREAD

**Issue by andygup** [Esri/angular-cli-esri-map#32]
Test with Angular 8. There will be some changes like query timings on `ViewChild`.

https://angular.io/guide/static-query-migration

**Comment by mamallama** [comment]
I tested the starter angular project and the only change I had to make was adding the `@ViewChild('mapViewNode', {static: true}) private mapViewEl: ElementRef;`

As far as I can tell, everything else is working as intended. :)

**Comment by andygup** [comment]
@mamallama thanks! I also noticed a small CSS change in the map component where I had to remove the height percentage and replace it with a specific height. I haven't researched that further yet.

```
.esri-view {
  height: 500px;
}

```

**Comment by andygup** [comment]
Closing. Updated repo to work with Angular 8. Switched from css to scss. Reference https://github.com/Esri/angular-cli-esri-map/commit/7aa92d9a892474ace22a7e1fb65c1ce8725bd26d. If there are any issues let me know.
