### ISSUE TITLE
Bootstrap Responsive Resizing 

### ISSUE THREAD

**Issue by tatemcg** [Esri/angular-cli-esri-map#33]
Hi all, 

Apology before hand if this isn't the right space for my questions.  I still relative new with Web development and especially with Angular.  I have managed to put together some code from ArcGIS JS v3 with Angular, but I can't seem get the map to resize correctly on the browser with bootstrap.  
Any help or tips on how to do this would be appreciated!  
Source code: https://github.com/tatemcg/nG-ArcGIS-JS3 

Thanks,

**Comment by andygup** [comment]
You'll just need to experiment with various css tweaks - I don't have an answer since I haven't worked with bootstrap + Angular. Also note that you may have to make additional adjustments when you migrate from Angular 7 to Angular 8.

The one specific suggestion I have is try tweaking the esri css. In Angular 7 you can set `.esri-view` as a percentage if you want.

```
.esri-view {
  height: 100%;
}
```

Reference https://github.com/Esri/angular-cli-esri-map/issues/32#issuecomment-505901391

If you figure it out please post more details and the solution.

**Comment by tatemcg** [comment]
thanks Andy,
I see that with ArcGIS JS v4  the map resizes/responsive without bootstrap? 
https://stackblitz.com/edit/angular-cli-esri-map2?file=src/main.ts

I guess I'm a little confuse as to why v3 doesn't when v4 does automatically.

**Comment by andygup** [comment]
Forgot to ask in my previous comment, how come you are using ArcGIS JS API 3.x? The 4.x API will be significantly more performant and responsive especially when used with 3rd party frameworks like Angular. 

Can you provide a .gif or screenshot of what you are seeing with the 3.x API?

**Comment by tatemcg** [comment]
Currently I'm using the the v3.x because I know it better than v4.x.  I'm not familiar as I am with v4.x as v3.x

Attached is the screenshots.
before resizing the browser 

![resize1](https://user-images.githubusercontent.com/52325547/60608368-f0a37980-9d84-11e9-8ebf-e603abcf2223.PNG)

After resizing the browser
![resize2](https://user-images.githubusercontent.com/52325547/60608402-02851c80-9d85-11e9-85b4-679c106c8b05.PNG)

**Comment by andygup** [comment]
Ah okay. Correct, in 3.x the map does not automatically recenter when the window changes size.  Here's one example of of how to build that functionality in 3.x: https://github.com/Esri/quickstart-map-js/blob/master/html/misc/autocenter.html#L95. I haven't tried to do that inside of an Angular component but in theory it should still work. Let me know if that helps?

**Comment by tatemcg** [comment]
Andy, I look at the link you pasted and copy over some code and put it in my esri.map.component.ts. 
			var resizeDelay = 100;
			map.on(map, 'load', function (map) {
				map.on(window, 'resize', map, map.resize);
			});
			map.on(map, 'resize',  function(extent, width, height) { 
				map.__resizeCenter = map.extent.getCenter();
				setTimeout(function() {
					map.centerAt(map.__resizeCenter);                
				}, resizeDelay);
			});

not sure what I'm doing, but it doesn't seem to work.

thanks,

**Comment by andygup** [comment]
Can you create a stackblitz that demonstrates what you are trying to do? That will be the easiest way to troubleshoot.

**Comment by tatemcg** [comment]
Andy, see below link.
https://stackblitz.com/edit/github-ft7vf9

You might see some irregularity on the mapview, it doesn't have that on my local PC.

**Comment by sardeenz** [comment]
@tatemcg If you're new, then I would recommend 4.12 and move on.

**Comment by andygup** [comment]
@tatemcg I don't see the map centering functionality? I think some of the irregularities you are seeing are because the map requires css, here's the syntax for that: `@import url('https://js.arcgis.com/3.28/esri/css/esri.css');`

**Comment by tatemcg** [comment]
Andy,
I used your css import syntax and it worked out the irregularities. 
I also added some of the code to try and get the map centering correctly, but I sure I did it wrong as well.

**Comment by andygup** [comment]
@tatemcg can you save the map centering changes to the stackblitz sample? I'm not seeing that code in the sample.

**Comment by tatemcg** [comment]
Andy,
It should already be in the stackblitz URL
https://stackblitz.com/edit/github-ft7vf9
![image](https://user-images.githubusercontent.com/52325547/60994228-b94d4380-a315-11e9-83f0-18b319dccdac.png)

Thanks,
