### ISSUE TITLE
Using arcgis-webpack-plugin with Angular 8

### ISSUE THREAD

**Issue by andygup** [Esri/angular-cli-esri-map#35]
I was able to get a prototype running using `arcgis-webpack-plugin` and Angular 8 CLI. 

There's still a little bit of testing that needs to be done before converting this repo over from `esri-loader`. And, please send me your feedback 😄.  The steps I took to build the prototype are outlined below. I "think" I captured everything from my notes, but let me know if I missed something.

1. Do a fresh install of an app using the Angular 8 CLI (latest). You can find more info here: https://cli.angular.io/. 
2. Install this handy helper for a custom webpack builder: 

     `npm i -D @angular-builders/custom-webpack`. 

    Here's the doc and code: https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack

3. Install arcgis-webpack-plugin:

    `npm install --save-dev @arcgis/webpack-plugin --verbose`. 

    Here's a reference to doc and code: https://github.com/Esri/arcgis-webpack-plugin

4. Install ArcGIS JS API types:

    `npm install --save @types/arcgis-js-api`

5. In `angular.json` under `projects.architect` I replaced `build` and `serve` with the following

```
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js"
            },
            "outputPath": "dist/angular-builder-esri",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "angular-builder-esri:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "angular-builder-esri:build:production"
            }
          }
        },

```
6. I made a few minor tweaks to `tsconfig.json`. I'm not sure what was 100% necessary since I was just trying to get things going, it will take more testing to determine which libs are needed for example.

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types",
      "./types"
    ],
    "lib": [
      "dom",
      "es2015.promise",
      "es5",
      "es6"
    ],
  }
}
```

7. Create a new file in root called `extra-webpack.config.js`:

```
const ArcGISPlugin = require('@arcgis/webpack-plugin');
/**
 * This is where you define your additional webpack configuration items to be appended to
 * the end of the webpack config.
 */
module.exports = {
  plugins: [new ArcGISPlugin()],
  node: {
    process: false,
    global: false,
    fs: "empty"
  }
};
```

8. In `tsconfig.app.json` add `"types": ["arcgis-js-api"]`

9. At this point I'd recommend doing a test serve by running `ng serve` and seeing if there are any errors. If there are errors then fix them now before moving on.

10. Generate the scaffolding for your mapping component

```
  ng g component esri-map
```

11. Copy the `app.components` contents from `angular-cli-esri-map/src/app` into your new `esri-app/src/app/` directory. Yep, I know, the `app.component.html` file still has some text referring to `esri-loader`, I'll fix that later.

12. Copy the contents from the `angular-cli-esri-map/src/app/esri-map` folder into your new `esri-app/src/app/esri-map` directory.
 
13. Replace the contents of `esri-map.components.ts` with the code from this gist: https://gist.github.com/andygup/b4736f8a7cc97a007a196dcb42af74cf

14 Give it a go: `ng serve`. This is definitely not optimized. It should compile without errors. Here's a partial screenshot of my build console messages. I had a few extra goodies in my test app so you can ignore the esri-geometry message:

![image](https://user-images.githubusercontent.com/510440/61914843-34f6e500-aeff-11e9-8cb5-1d081f9ba015.png)

And here's the app running

![image](https://user-images.githubusercontent.com/510440/61914931-8e5f1400-aeff-11e9-82db-9d8a23faa59a.png)

**Comment by sbuscher** [comment]
Successful but took over 60s to compile the 2700+ modules.

**Comment by andygup** [comment]
Thanks @sbuscher! Yep, the initial load will take a while, plus I didn't do any optimization via module exclusion which can decrease the number of generated bundles => https://github.com/Esri/arcgis-webpack-plugin#excluding-modules.  Note-to-self to doc that in the README.

**Comment by sbuscher** [comment]
Glad to see that you are making good progress with removing esri-loader. Keep up the good work!

**Comment by andygup** [comment]
Closing. The webpack project is now available here: https://github.com/Esri/angular-cli-esri-map/tree/arcgis-webpack-angular

**Comment by RyannGalea** [comment]
Is there any way to get this working well with AOT: true ?

**Comment by MohdTalib368** [comment]
[ArcGIS.txt](https://github.com/Esri/angular-cli-esri-map/files/6585622/ArcGIS.txt)
This is my HTML page that is save txt file and in this i created WebMap with featurelayer in ArcGIS Javascript but i want to that convert in angular so pls how can i do this.
