### ISSUE TITLE
Need Help Converting to Angular Code

### ISSUE THREAD

**Issue by tatemcg** [Esri/angular-cli-esri-map#39]
Hello everyone.  I have some code that I wrote with the normal ArcGIS Javascript v4 style.  Now I'm trying to get the same result with Angular.  But its not working out as expected, the hovering with graphic is not displaying, the querying out the feature is not displaying in console or browser.  
Any help to determine where I went wrong would be much appreciated.

Github  repo: https://github.com/tatemcg/ng-esri-jsv4/blob/master/src/app/esri-map/esri-map.component.ts 
StackBlitz: https://stackblitz.com/github/tatemcg/ng-esri-jsv4

Below are my code that I'm trying to convert to Angular. 

[v4_3.txt](https://github.com/Esri/angular-cli-esri-map/files/3611858/v4_3.txt)

**Comment by andygup** [comment]
@tatemcg Usually there's not really anything in Angular that would prevent the ArcGIS JS API code from running correctly. Can you share a codepen or jsbin that shows the code running in a stand-alone JavaScript app?

**Comment by andygup** [comment]
On the `pointer-move` event I wrapped the calls to `changeCursor()` and `getGraphics` in a try/catch block. I'm seeing some previous silent errors. Maybe you can dig into those?

```javascript
                view.hitTest(screenPoint)
                  .then(function (response) {
                    console.log("response", response);

                    // if (response.results.length) {
                    //   var graphic = response.results.filter(dataResult => {
                    //     return dataResult.graphic.layer === layerFeature;
                    //   })[0].graphic;
                    // }
                    try {
                      changeCursor(response);
                      getGraphics(response);
                    }
                    catch(e){
                      console.error(e);
                    }
                  });
              });

```

![image](https://user-images.githubusercontent.com/510440/64986807-110faa00-d885-11e9-85a9-63c0773f4dd6.png)

**Comment by tatemcg** [comment]
Thanks Andy. It was a silly mistake the name of the element didn't match.  So I updated my repo and stackblitz and now the hovering works fine as expected.  But I can't still get the feature attributes out.

**Comment by andygup** [comment]
I'm going to go ahead and close this. Maybe you can bump over to  GeoNET to get your JS API questions answered? I'm sure you'll agree, this isn't an Angular issue.
