### ISSUE TITLE
Webpack example running tests fails

### ISSUE THREAD

**Issue by matsek-ihsm** [Esri/angular-cli-esri-map#49]
Hi!
Currently tests are failing on arcgis-webpack-angular.
Is there any way to run tests with arcgis webpack plugin?

I saw one solution with switching to Jest test runner and using moduleNameMapper, but is there any way to test application which is using arcgis webpack with karma test runner?

**Comment by andygup** [comment]
Yep, the failing karma tests are a known issue and I haven't had a chance to look into it. From what I remember esri, dojo and digit modules weren't resolving correctly. Probably have to specify the arcgis-webpack-plugin in karma config and possibly create a separate webpack-test.config.

**Comment by HawkPK** [comment]
I have a similar one. I am using Angular 9. I got the following error: ' Cannot find namespace '__esri'.' I tried a few solution even what @andygup proposed but they did not work. I found this thread: [Has](https://community.esri.com/thread/248351-karma-error-esri-is-not-defined#comments) and it was directed me here. Has somebody resolved this issues successfully ? Thank you

**Comment by hokivpn** [comment]
Any update on this issue or at least a workaround ?

**Comment by andygup** [comment]
No workaround, yet, I haven't had time to work on it. However, we are making great progress on an ESM build of the ArcGIS API for JavaScript that will be available later this year or early next year. Once we have that, it will be significantly easier to build tests.

I'll also check with a few folks here that hinted they might have solved the issue using our AMD build.

**Comment by mfcallahan** [comment]
Any update on this issue?

**Comment by andygup** [comment]
@mfcallahan No update on the tests, we've been focused on the ES modules (beta). That build will be available in a few weeks along with the 4.18 release. You can try out the pre-release version of the ES modules today:

```
npm install @arcgis/core
```

**Comment by mfcallahan** [comment]
Awesome, I'm going to give it a try!  I've been looking forward to version of the API which which can be included in an app directly thru npm.  Is there a roadmap or FAQ for the future of the ArcGIS API for JavaScript?  I'm curious to know what the path forward looks like as far as Esri supporting the AMD modules, the Webpack plugin, the esri-loader, and npm.

**Comment by andygup** [comment]
Just small tweaks, really. AMD modules will continue to be shipped for the foreseeable future for CDN and local builds. Webpack-plugin will still be shipped and it will get an [update to provide helper capabilities](https://github.com/Esri/arcgis-webpack-plugin/tree/update-for-esm) when using the ES modules. Esri-loader will still be available, it will just get a README update.

**Comment by andygup** [comment]
Closing.
