### ISSUE TITLE
ERROR in src/app/esri-map/esri-map.component.ts(24,15): error TS2503: Cannot find namespace '__esri'.

### ISSUE THREAD

**Issue by jplew** [Esri/angular-cli-esri-map#5]
Hi:

I followed all the installation instructions for a brand new Angular CLI 6 project. When I run `ng serve`, Webpack gives the following error at compile-time:

    ERROR in src/app/esri-map/esri-map.component.ts(24,15): error TS2503: Cannot find namespace '__esri'.

Please not that this error does not impact functionality. The maps loads just fine in the browser, and `esri-map.component.ts` is finding the correct typings from `@types/arcgis-js-api/index.d.ts`. I'm just giving you a heads up.

Here is my `package.json`:

```
  "dependencies": {
    "@angular/animations": "^6.0.0-rc.5",
    "@angular/common": "^6.0.0-rc.5",
    "@angular/compiler": "^6.0.0-rc.5",
    "@angular/core": "^6.0.0-rc.5",
    "@angular/forms": "^6.0.0-rc.5",
    "@angular/http": "^6.0.0-rc.5",
    "@angular/platform-browser": "^6.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^6.0.0-rc.5",
    "@angular/router": "^6.0.0-rc.5",
    "@types/arcgis-js-api": "^4.6.0",
    "core-js": "^2.5.4",
    "esri-loader": "^2.2.0",
    "rxjs": "^6.0.0-uncanny-rc.7",
    "rxjs-compat": "^6.0.0-uncanny-rc.7",
    "zone.js": "^0.8.24"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.5.0",
    "@angular/cli": "~6.0.0-rc.4",
    "@angular/compiler-cli": "^6.0.0-rc.5",
    "@angular/language-service": "^6.0.0-rc.5",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "prettier": "^1.10.2",
    "tslint-config-prettier": "^1.7.0"
  }
```

**Comment by jplew** [comment]
error seems to have gone away after I fixed my tests. Not sure if there's any connection. 
Everything seems to work fine with Angular 6 as of now.

**Comment by andygup** [comment]
@jplew weird, thanks for the heads-up.

Also curious, which version of Angular 6 are you using, e.g. `6.0.0 rc5`?

**Comment by jplew** [comment]
Yes, using `6.0.0 rc5`.

It might be related to this: https://github.com/Esri/angular-cli-esri-map/issues/3. 

Perhaps the error appears only the first time a user runs `ng serve`. I didn't see it after that.

**Comment by mixalistzikas** [comment]
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "outDir": "./out-tsc/app",
        "types": [
            "arcgis-js-api"
        ]
    },
    "files": [
        "src/main.ts",
        "src/polyfills.ts"
    ],
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "src/test.ts",
        "src/**/*.spec.ts"
    ]
    }


Add "arcgis-js-api"
