### ISSUE TITLE
How to resolve importScripts?

### ISSUE THREAD

**Issue by RyannGalea** [Esri/angular-cli-esri-map#52]
Using the Angular webpack implementation I am having an issue where it seemingly is trying to resolve dojo scripts locally?

```
dojo.js:6 DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:4200/dojo/arcgis-js-api/views/2d/engine/vectorTiles/WorkerTileHandler.js' failed to load.
```

How do I fix this issue?

**Comment by RyannGalea** [comment]
It seems I have all these files in my node_modules in the 'arcgis-js-api' folder although I do not know how to forward the esriConfig to it?

I am reading about dojoConfig but again I do not know how to implement this with Angular

**Comment by andygup** [comment]
Can you share a code snippet of what you are trying to do?

**Comment by RyannGalea** [comment]
specific issue re

**Comment by RyannGalea** [comment]
I have noticed now I can actually resolve that file using this link opposed to where it's trying to locate it:
```
https://js.arcgis.com/4.14/esri/views/2d/layers/features/Pipeline.js
```
Just not sure how to adapt the config to use this correct link.

**Comment by RyannGalea** [comment]
Ok, well I have figure out that I had to add this line:
```
{ name: "arcgis-js-api", location: `${DEFAULT_WORKER_URL}esri` },
```
to my loaderConfig packages, this has resolved this issue for now.

**Comment by andygup** [comment]
I'm testing Angular 9 and I was able to get `topo-vector` to work using all the project defaults without modifying any config files except to update the node packages. Something might have changed that fixed the issue:

`"@arcgis/webpack-plugin": "^4.14.1"`
`"@angular/core": "~9.0.2"`
`"@angular/cli": "~9.0.2"`
`"@angular-builders/custom-webpack": "^8.4.1"`

**Comment by RyannGalea** [comment]
@andygup, Thanks for the update, will test this out at soon.
