### ISSUE TITLE
esri-view not working when used height=100%

### ISSUE THREAD

**Issue by hishamshrideh** [Esri/angular-cli-esri-map#66]
esri-view not showing when used height percentage in esri-view class
it showing only when provide the height in pixel !

esri view {
height:100%
}

**Comment by andygup** [comment]
It's not really obvious how to make that work. I'll make a note to change the sample. 

Try this:

```javascript
.esri-view {
  height: 100vh;
}
```

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/length

**Comment by hishamshrideh** [comment]
Hi andy,

Thanks for your quick response 
Using vh its get a full height but with scroll in home page. 

Do you have idea how fix it !? Make it without scrolling

**Comment by andygup** [comment]
Unfortunately, it's a very common question but there isn't a one-size-fits-all answer. You'll have to do some investigation and testing to figure that out. I recommend doing some internet investigating and try different things to get it exactly the way you want it. I'm not a CSS expert, but the very basic theory looks something like this. 

```
.esri-view {
     // 105px represents the combined height of the elements above the map
     height: calc(100vh - 105px); 
}
```

**Comment by hishamshrideh** [comment]
Thanks andy for your continuous suppprt

You are hero of angular gis developer

I'll appreciate your quick help @andygup

**Comment by andygup** [comment]
Glad to help. I'l go ahead and close this, reach out again if you get stuck.
