### ISSUE TITLE
esriSignInDialog broken in JS API 4.15 using the Angular CLI and esri-loader

### ISSUE THREAD

**Issue by slead** [Esri/angular-cli-esri-map#68]
I'm finding that the login window, which appears when using a resource that requires authentication, is not working with ArcGIS Server JS API version 4.15 and the Angular CLI with esri-loader.

To reproduce, modify the sample app to use a secure `webmap` and `esriConfig` pointing to your portal (in place of a simple `map` object):

```
      const [EsriWebMap, EsriMapView, esriConfig] = await loadModules([
        "esri/WebMap",
        "esri/views/MapView",
        "esri/config"
      ]);

      esriConfig.portalUrl = "https://path-to-the-portal";
      const webMap: esri.WebMap = new EsriWebMap({
        portalItem: {
          id: "secure-item-id"
        }
      })
```
Then initialise the view against the `webmap` item. The "sign in" dialog should appear in a modal popup, but using version 4.15 of the ArcGIS Server JS API it appears outside of the `app-root` object.

![sign in](https://user-images.githubusercontent.com/133596/84353020-b764c200-ac01-11ea-95e6-5c1485a0699a.PNG)

In this example it's still useable, but in my case I have a full-screen map so the sign-in dialog is appearing underneath the map and so can't be accessed.

If I manually downgrade the ArcGIS Server JS API version to 4.14 in the esri-loader configuration, the sign-in dialog works as expected, so the problem appears to have been introduced in version 4.15.

Thanks for any advice

**Comment by andygup** [comment]
@slead make sure your JS API css version matches your JS API library version. Here's an example that's working on my machine: https://stackblitz.com/edit/angular-cli-esri-map3-login-test?file=src%2Fapp%2Fesri-map%2Fesri-map.component.ts  and here's the [css setting](https://stackblitz.com/edit/angular-cli-esri-map3-login-test?file=src%2Fapp%2Fesri-map%2Fesri-map.component.css).

![image](https://user-images.githubusercontent.com/510440/84401795-ead32c80-abc0-11ea-8b1d-8285b3958c02.png)

**Comment by slead** [comment]
Thanks for the fast response. I didn't realise that the CSS loading was handled separately - I thought that esri-loader handled it along with the JS files.

**Comment by andygup** [comment]
For other folks reading this issue, go here for more information on loading css with esri-loader: https://github.com/Esri/esri-loader#when-you-load-the-script. 

The reason why the css is loaded with the component in this example is because of historical issues related to app lifecycle + map lifecycle. I haven't tested it in a while, but it's probably okay with Angular 8+ to use esri-loader's css management pattern to load the css. Test it and see what you find. If you do have some test results please share here in this issue.
