### ISSUE TITLE
How do I enable WebGL rendering?

### ISSUE THREAD

**Issue by jplew** [Esri/angular-cli-esri-map#7]
Hi:

I originally meant to file this as an issue/question, but I poked around the codebase and got my answer. I'm leaving this here to serve as documentation in case anyone else gets stuck.

-----------------------

[The ArcGIS docs](https://developers.arcgis.com/javascript/latest/sample-code/layers-featurelayer-webgl/index.html) recommend using WebGL rendering rather than default SVG rendering for creating client-side Feature Layers. 

In order to do this, the docs say:

    To enable WebGL rendering for FeatureLayers, paste the following script in your application prior to loading the ArcGIS API for JavaScript:

        <script>
          var dojoConfig = {
            has: {
              "esri-featurelayer-webgl": 1
            }
          };
        </script>

In order to ensure that this flag is set before the main ArcGIS script gets loaded, all you need to do is pass it as the second argument in the `loadingModules` method (imported from `esri-loader`, located at  `node_modules/esri-loader/dist/esm/esri-loader.js`). 

So all you need to change is this:

    public ngOnInit() {

      const dojoConfig = {
        has: {
          'esri-featurelayer-webgl': 1
        }
      }

      loadModules([
        'esri/WebMap',
        'esri/Map',
        'esri/views/MapView',
        'esri/widgets/Search',
        'esri/layers/MapImageLayer'
        'esri/layers/FeatureLayer'
      ], { dojoConfig } ) // <---- add custom options
        .then(([WebMap, EsriMap, MapView, Search, MapImageLayer, FeatureLayer]) => {

I did notice a speed boost in loading my map, but haven't confirmed 100% that WebGL is loading. So if you think there's a better way do let me know. Thanks.

**Comment by andygup** [comment]
@jplew good catch. That's the correct way to do it. WebGL is eventually going to become the default and you won't have to set the flag. You'll really notice the performance difference as you pan the map with thousands of features.

**Comment by tif-p-st** [comment]
Hi @andygup, is there a timeline on wen webGL will become the default (if it has not already happened yet)? Also will it also be enabled for GraphicsLayer? Thanks in advance for your reply!

**Comment by andygup** [comment]
As of 4.10, all drawing in 2D MapView is WebGL.  Reference: https://developers.arcgis.com/javascript/latest/guide/4.10/index.html

More info on browser and hardware supported can be found here: https://developers.arcgis.com/javascript/latest/guide/system-requirements/

**Comment by tif-p-st** [comment]
Thanks @andygup !

**Comment by MohdTalib368** [comment]
i am getting this error when i work ArcGIS map with angular [esri.views.2d.engine.webgl.TextureManager] 

my code look like 👍 initializeMap(): Promise<any> {

        //debugger;
        const container = this.mapViewEl.nativeElement;
        const layer = new FeatureLayer({
            url: "here is url",
            outFields: ["*"]
        });
        const webmap = new WebMap({
            portalItem: {
               
                id: '',
            },
        });
        const view = new MapView({
            container,
            map: webmap,

        });
        // view.when(function () {
        //     var layerList = new LayerList({
        //         view: view

        //     });
        //     view.ui.add(layerList, "top-right");
        // });
        const layerList = new LayerList({
            container: document.createElement("div"),
            view: view
        });
        const layerListExpand = new Expand({
            expandIconClass: "esri-icon-layer-list",  // see https://developers.arcgis.com/javascript/latest/guide/esri-icon-font/
            // expandTooltip: "Expand LayerList", // optional, defaults to "Expand" for English locale
            view: view,
            content: layerList

        });
        view.ui.add(layerListExpand, "top-right");
        var basemapGallery = new BasemapGallery({
            view: view,
            container: document.createElement("div")
        });
        var bgExpand = new Expand({
            view: view,
            content: basemapGallery
        });

        basemapGallery.watch("activeBasemap", function () {
            var mobileSize = view.heightBreakpoint === "xsmall" || view.widthBreakpoint === "xsmall";

            if (mobileSize) {
                bgExpand.collapse();
            }
        });
        view.ui.add(bgExpand, "top-right");
![arcgiserror](https://user-images.githubusercontent.com/62232516/125036840-4f70ed00-e048-11eb-86b1-d1252e580e0f.PNG)
How can i resolve this pls help

**Comment by andygup** [comment]
@MohdTalib368 That error is a font issue with your portal item and not a problem with Angular. You should be able to recreate the error in a vanilla JS app, the error is saying you need to update a font in the portal item. I recommend searching/posting on the community site to see if anyone else had the same issue: https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript.
