### ISSUE TITLE
Destroying the map - memory leak

### ISSUE THREAD

**Issue by docmur** [Esri/angular-cli-esri-map#75]
Good Day

If you add a button that removes / adds the map with an ngIf, the memory the map held isn't getting free'd. 

`<button (click)="map = false">Disable Map</button>
<button (click)="map = true">Enable Map</button>

<ng-container *ngIf="!_map">
</ng-container>

<ng-container *ngIf="_map">
  <app-esri-map
    [center]="mapCenter"
    [basemap]="basemapType"
    [zoom]="mapZoomLevel"
    (mapLoadedEvent)="mapLoadedEvent($event)">
  </app-esri-map>
</ng-container>`

How can the map be fully destroyed, including the WebGL context?

**Comment by andygup** [comment]
Take a look at my write-up here: https://community.esri.com/thread/258078-memory-issue-arcgis-414-angular-memory-not-getting-freed. The best practice is create a service that recycles the MapViews and DOM nodes.

**Comment by andygup** [comment]
So, some good news is we just added a view.destroy() method in the /next build of the JS API that you can test it out before the next release (4.17 - Early October 2020): https://github.com/Esri/feedback-js-api-next. If you have a chance to test it, let us know how if you run into any issues? I'm going to close out this issue for now.

```
// Unset map from the view so that it is not destroyed
const map = view.map;
view.map = null;

// Coming in 4.17 - destroy the view and all attached resources
view.destroy();
```
