### ISSUE TITLE
How to import modules outside of loadModules()?

### ISSUE THREAD

**Issue by jplew** [Esri/angular-cli-esri-map#8]
I am trying to rewrite the Sample Code for ["Create a FeatureLayer with client side graphics"](https://developers.arcgis.com/javascript/latest/sample-code/layers-featurelayer-collection/index.html) in Typescript rather than plain JS. I got all my red squigglies to go away but am running into an issue at compile-time because of my imports.

I know I can load modules like this:
 
    public ngOnInit() {
      loadModules([
        'esri/views/MapView',
        'esri/Map',
        'esri/geometry/Point',
        'esri/widgets/Legend',
        'esri/request'
      ])
        .then(([MapView, EsriMap, EsriPoint, EsriLegend, EsriRequest]) => {

However, this scopes my `EsriLegend` variable to my `then` block. I want to reuse it in another method outside. For example I want to go `const legend = new EsriLegend()` in a helper function defined outside of `ngOnInit`. 

To achieve this, I tried:

    import * as Legend from 'esri/widgets/Legend'

But the compiler complains:

    Module not found: Error: Can't resolve 'esri/widgets/Legend' in '~/projects/topcoder/dubai/rta/src/app/map'

I then tried this (like [the docs](https://developers.arcgis.com/javascript/latest/guide/typescript-setup/index.html) curiously seem to recommend):

    import Legend = require('esri/widgets/Legend')

But got this error instead:

    ERROR in src/app/map/map.component.ts(28,1): error TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

Here is my full attempt at a Typescript rewrite: https://gist.github.com/jplew/c0ebade552034ea1630ec05067bd18e4

Thanks very much.

**Comment by jplew** [comment]
**Update**

The following appears to work but I have to test more:
 
    const legend = new esri.Legend()

**Comment by andygup** [comment]
Another good documentation topic. We need to doc the `esri` namespace better.

**Comment by andygup** [comment]
Did you try moving `import esri = __esri` up to this line: https://gist.github.com/jplew/cf61707f727dfe8fb897f838ee444af4#file-map-component-ts-L24?

Each component that uses esri types has to have that reference. As long as the esri types have been installed and exist under the `node_modules` directory then "in general" you should be good.

**Comment by jplew** [comment]
**Update**

I managed to get everything working by importing my modules using `loadModules`, then inlining my methods inside `ngOnInit()`. Here is a working example: https://gist.github.com/jplew/869db9a0db818d212a3d98ae5ac58fd6#file-map-component-ts-L360

**Comment by perfectr** [comment]
Just adding a +1 from me. I'd like to use this library too but like jplew I'm struggling a bit understanding how to integrate the examples from the Esri website with this Angular based approach. In particular I've hit a roadblock around the use of JSX. Looking forward to any pointers you  might be able to give.

**Comment by jplew** [comment]
@perfectr 

Haven't looked at them myself, but have you checked out these React-specific repos?
 
https://github.com/davetimmins/arcgis-react-redux-legend
https://github.com/davetimmins/esri-loader-react
https://github.com/nicksenger/react-arcgis

**Comment by andygup** [comment]
@perfectr yep, we are only planning on providing typescript/javascript samples for Angular 5 and 6. You are welcome open Angular/JSX related issues and hopefully folks in the community can provide answers.

**Comment by andygup** [comment]
Here are a few comments that will hopefully help to clarify some of the questions above: 
* The use of Esri typings is optional. 😀 Typescript is designed as a compile-time productivity tool and works great to reduce errors and bugs. If it's causing you headaches then it's easy to remove the typings to get things working and revisit the issue later, IMHO.
* The `Promise` callback scope for `esri-loader` is standard JavaScript scoping. Here are a few reference articles that may help others understand what's going on: https://www.w3schools.com/js/js_scope.asp, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures
* There are more advanced Angular samples here: https://github.com/sean-olson-e/Angular-and-the-ArcGIS-API-for-JavaScript
