### ISSUE TITLE
Error on executing npm install command for ESRI webPack

### ISSUE THREAD

**Issue by Maazpatel111** [Esri/angular-cli-esri-map#87]
Hi ,

I am getting issue like "**undefined ls-remote -h -t ssh://git@github.com/Esri/dojox.git**" when executing the npm install command for the webpack version.
 there is another warning is also running continuously in terminal like **no such file or directory, open 'E:\angular-cli-esri-map\node_modules\.staging\type-847b7516\test\safe-integer\ensure.js'**

how can I add this library or is there any workaround on this?

**Comment by andygup** [comment]
That's very strange. I just re-cloned this branch and wasn't able to reproduce your issues. 

Are you running the app in the `arcgis-webpack-angular` branch of this repo, or your own app?

**Comment by andygup** [comment]
Closing as inactive. Feel free to provide followup info, if needed.
