### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by harafat007** [Esri/angular-cli-esri-map#89]
Hello, When I am running npm install on the code downloaded from the arcgis-webpack-angular branch I am getting various errors like :
19753 warn tar ENOENT: no such file or directory, lstat 'D:\TechnicalCode\AngularArcGIS\angular-cli-esri-map-arcgis-webpack-angular\node_modules\.staging\aria-query-585221cf\lib\etc\roles\dpub'
19754 warn tar ENOENT: no such file or directory, open 'D:\TechnicalCode\AngularArcGIS\angular-cli-esri-map-arcgis-webpack-angular\node_modules\.staging\rxjs-78aaf8f2\util\TimeoutError.js'
19755 warn tar ENOENT: no such file or directory, open 'D:\TechnicalCode\AngularArcGIS\angular-cli-esri-map-arcgis-webpack-angular\node_modules\.staging\rxjs-0a2353dd\internal\util\TimeoutError.js'

I am attaching the debu.log file. I tried running npm install multiple times but got same error.
[2020-11-09T20_02_13_168Z-debug.log](https://github.com/Esri/angular-cli-esri-map/files/5513086/2020-11-09T20_02_13_168Z-debug.log)

**Comment by andygup** [comment]
Try deleting `node_modules` directory and `package-lock.json` and then try reinstalling.

**Comment by andygup** [comment]
Another recommendation for this is to try the new JS API ES modules when they go into beta next month. You can try them out now using `npm install @arcgis/core`. Closing...

**Comment by harafat007** [comment]
Thanks Andy !
