### ISSUE TITLE
Where to paste Arcade expressions?

### ISSUE THREAD

**Issue by jplew** [Esri/angular-cli-esri-map#9]
According to [the official docs](https://developers.arcgis.com/javascript/latest/guide/arcade/index.html), arcade expressions are supposed to be placed between `<script>` tags:

    When writing multi-line expressions, we recommend you place it in a separate <script> tag outside the JavaScript portion of the app, and set the type to text/plain with a unique ID you can use to reference the script in the appropriate place within JavaScript.

    <script type="text/plain" id="adult-population">
      // place multi-line Arcade expression here
    </script>
    Then you can reference the script as a string value by calling the document.getElementById() method.

    renderer.valueExpression = document.getElementById("adult-population").text;

Is there a better way to do this in Angular? I ask because in Angular, as far as I know, you're not supposed to reference DOM elements directly.

I tried placing an expression like that in my `index.html`. It works, but it's quite silly because you can't use ES6 features like `const` or arrow functions, because that JS snippet is being run by the browser which doesn't support those those features natively.

**Comment by andygup** [comment]
You can wrap the arcade expression as a multi-line String using backtick delimiters.

Psuedo-code Example:

```JavaScript
   const arcadeExpression = 
     `
      var pickup_time = Date($feature.pickup_datetime);
      var dropoff_time = Date($feature.dropoff_datetime);
      var time_difference = DateDiff(dropoff_time, pickup_time, 'milliseconds');
  
      if(time_difference > (30 * 60000)){
            return true; // trip longer than 30 min's
       }
       else {
            return false; // trip shorter than 30 min's
       }
       `;

      . . . 
  
      renderer.valueExpression = arcadeExpression;
     
```

**Comment by jplew** [comment]
good solution, thanks for the tip!
