### ISSUE TITLE
Deprecation notice - update repo for ArcGIS JS API ES modules (beta) at 4.18

### ISSUE THREAD

**Issue by andygup** [Esri/angular-cli-esri-map#90]
We are excited to announce that at 4.18 (December 2020), the ArcGIS API for JavaScript will  available as ES modules (beta) for use with local builds via [npm @arcgis/core](https://www.npmjs.com/package/@arcgis/core). More info can be found in this [early announcement blog post](https://www.esri.com/arcgis-blog/products/js-api-arcgis/announcements/es-modules-are-coming-soon-in-the-arcgis-api-for-javascript/).

The draft plan is to reorganize this repo and consolidate everything back into the main branch. This will involve breaking changes to the current organization that contains multiple branches.
* Main branch
   - README 
      - As of 4.18 there are two approaches:
         - `npm install` (ESM build) - This will be the recommended approach and the modules will be bundled with the build. `npm install @arcgis/core` will be superseding the need to use `arcgis-webpack-plugin` and the additional configuration that comes with it. For a working sample, link to the new ES module samples on the jsapi-resource repo.
         - Lazy loading modules at runtime via `esri-loader` - these modules are lazy-loaded at runtime from a CDN using a `loadModules()` pattern and are not bundled with the build. 
      - Brief explanation that the repo is only tested against the latest shipping version of Angular.
      - **Delete** the arcgis-webpack-plugin branch and just provide a link to the old commit if someone wants to see how to use it.
   - /esri-loader-sample - this will be the only working sample in the repo.

**Comment by andygup** [comment]
Modifying the draft plan above - most likely this repo will be deprecated at 4.18 and point to the new grouping of esm-samples on the jsapi-resource repo. 

Reference: https://github.com/Esri/jsapi-resources/pull/229

**Comment by nbabel** [comment]
Is using webpack with version 4.17 or 4.16 still supported?  My app based on this repo suddenly stopped working and will no longer build.  I've tried switching to v4.16 and 4.17 and I'm getting all kinds of errors.  Modules are not found, dojo is not loaded, critical dependency.  So if we have an app based on this repo are we being forced to upgrade to 4.18?  I do plan on upgrading but need my app to work in the mean time until I can make the upgrade.

**Comment by andygup** [comment]
Yes, webpack is definitely still supported! Can you open a new issue on this repo?

**Comment by nbabel** [comment]
I was able to get v4.16 to work.  Still getting errors with v4.17.

**Comment by andygup** [comment]
@nbabel can you open a new issue and provide details on the errors?

**Comment by bpo19** [comment]
I am writing an Angular library that is using the ArcGIS JS API with esri-loader. Currently we are struggling with the upgrade from 4.16 to 4.19. We don't want to switch to ES modules yet, and according to the documentation, https://developers.arcgis.com/javascript/latest/tooling-intro/, the AMD modules will be available for the foreseeable future.

To me, making this repo deprecated is a bad decision. We really need an Angular example working with the latest ArcGIS JS API loaded with CDN/AMD modules and esri-loader. Starting with the version 4.18 we are observing `Unhandled Promise rejection` errors thrown in the console by some Esri objects such as BasemapGallery or SceneView. There must have been a change in the ArcGIS JS API code between versions 4.17 and 4.18 that is triggering the issue in the Angular context. I will provide more details in separate issues.

Is there an option that you keep this repo maintained and updated to the latest Esri & Angular versions? If not, can you point me  some other place where I can find a working Angular/ArcGIS/esri-loader example and submit issues occurring only in such context?

Thanks!

**Comment by andygup** [comment]
Whoops, @bpo19 I'm just seeing your comment. We are focusing our resources on supporting the latest JS frameworks and build tools which recognize ES modules as a best practice for building applications. Feel free to post issues for now, we'll try to answer questions but our ability to help troubleshoot will be very limited. Note some issues have been resolved in newer versions of Angular, this repo is frozen at Angular 11. 

With regards to the `unhandled promise rejections` there is a known issue with potential workarounds. See the comments here in the esm-samples repo: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli#known-issues. 

* To prevent Unhandled Promise Rejection errors when using Angular with Zone.js, upgrade to Angular 13, Zone.js 0.11.4 or greater, and switch the tsconfig.target to es2017 or greater.

**Comment by andygup** [comment]
Closing. Deprecation notice was posted at 4.18 and will be retired at 4.22. Reference issue #114.
