### ISSUE TITLE
Where is urlUtils imported from?

### ISSUE THREAD

**Issue by forrestlin100** [Esri/angular-cli-esri-map#95]
import urlUtils from '@arcgis/core/core/urlUtils';

This doesn't work.

**Comment by andygup** [comment]
There's no default export on that module. Try something like `import { urlToObject} from '@arcgis/core/core/urlUtils';`

**Comment by forrestlin100** [comment]
I do import { urlToObject} from '@arcgis/core/core/urlUtils'

But there is no addProxyRule with urlToObject:

urlToObject.addProxyRule({
     urlPrefix: "https://www.mycompany.com/server",
     proxyUrl: "https://www.mycompany.com/Proxy/proxy.ashx"
    });

**Comment by andygup** [comment]
Oh! Do something like this:

```js
import * as urlUtils from '@arcgis/core/core/urlUtils';

urlUtils.addProxyRule( . . . );

```

**Comment by forrestlin100** [comment]
Thanks.

**Comment by andygup** [comment]
Awesome, I'll go ahead and close this issue.
