### ISSUE TITLE
Uncaught ReferenceError: __esri is not defined

### ISSUE THREAD

**Issue by pvitt** [Esri/angular-cli-esri-map#96]
Hi - I need to use the esri library (specifically webMercatorUtils) outside of the ngOnInit Method. I'm using esri-loader 
with Angular 11 and am trying to import the library in my component code as shown below, but keep getting the error 
'Uncaught ReferenceError: __esri is not defined' at run time.  I've installed the esri typescript library and confirmed
they are located in my node_modules\@types\arcgis-js-api directory.  I've also added the line "types": ["arcgis-js-api"] 
in my tsconfig.json, tsconfig.app.json and tsconfig.spec.json.  I see that this issue was brought up in 2018 
 (https://github.com/Esri/angular-cli-esri-map/issues/8) and it was memtioned that the namespace issue might be resolved with a new TS 2.9 pattern.

Are there any developments on the 2.9 pattern? Is there anything else you can see that I could try to get this working?
If I were to use the new ES modules (https://developers.arcgis.com/javascript/latest/tooling-intro/)
would that remove this problem?

Thanks 

Pete

import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

import { loadModules } from 'esri-loader';
import esri = __esri// error occurs here

@Component({
  selector: 'app-mt-map',
  templateUrl: './mt-map.component.html',
  styleUrls: ['./mt-map.component.css']
})
export class MtMapComponent implements OnInit {
  @ViewChild('mapViewNode') private mapViewEl: ElementRef;

  mapView: esri.MapView;
  constructor() { }

  ngOnInit(): void {
    loadModules([
      'esri/Map',
      'esri/views/MapView',
      'esri/geometry/support/webMercatorUtils'
    ])
....

**Comment by andygup** [comment]
Do you need the TypeScript types? They aren't required and you could remove them if you don't need them.

You can always try the ES modules, since I'm not sure why you are having the error it makes sense for you to test them out: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli

**Comment by pvitt** [comment]
> Do you need the TypeScript types? They aren't required and you could remove them if you don't need them.
> 
> You can always try the ES modules, since I'm not sure why you are having the error it makes sense for you to test them out: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli

Thanks Andy.  I tried removing the Typescript types and the project wouldn't build.  I started fresh with a copy of the app-scaffolding app.  It compiled and ran until I added a new method outside of NgOnInit that references the esri library.  After I did this an error was thrown here:
import esri = __esri; // Esri TypeScript Types --> Uncaught ReferenceError: __esri is not defined
Attached is the revised esri-map.component.ts with the method added
[esri-map.component.txt](https://github.com/Esri/angular-cli-esri-map/files/5999071/esri-map.component.txt)

I'll try the ES Modules now I guess

**Comment by andygup** [comment]
> It compiled and ran until I added a new method outside of NgOnInit that references the esri library. 

What's your use case for running a method before ngOnInit()? You could try running your method in the constructor. Using ngOnInit is a best practice for obeying the Angular component lifecycle. If you run stuff outside of the lifecycle then you can oftentimes run into unexpected problems.

**Comment by pvitt** [comment]
> > It compiled and ran until I added a new method outside of NgOnInit that references the esri library.
> 
> What's your use case for running a method before ngOnInit()? You could try running your method in the constructor. Using ngOnInit is a best practice for obeying the Angular component lifecycle. If you run stuff outside of the lifecycle then you can oftentimes run into unexpected problems.

Hi Andy - I'm following your suggestion of moving the method to NgOnInit.  The Observer sample I think will work for my case

**Comment by andygup** [comment]
Closing.
